"""
Configuration for Closed-Loop Robotic Exosuit Digital Twin
==========================================================
All tunable parameters in one place.

Loading targets are now derived from REAL OpenSim Joint
Reaction Analysis output (Gait2354 model, subject01 walking
trial). The calibration was generated by parse_jra.py from
the validated CMC muscle force results.

Reference for the pipeline:
    Delp et al. (2007) — OpenSim
    John et al. (2013) — CMC validation for Gait2354
"""

import os
import sys
import json

# ─── OpenSim setup (Windows) ─────────────────────────────
OPENSIM_BIN = r"D:\Program Files\OpenSim\OpenSim 4.5\bin"
OPENSIM_PYTHON = r"D:\Program Files\OpenSim\OpenSim 4.5\sdk\Python"

try:
    os.add_dll_directory(OPENSIM_BIN)
    os.environ['PATH'] = OPENSIM_BIN + ';' + os.environ['PATH']
    sys.path.insert(0, OPENSIM_PYTHON)
except Exception:
    pass

# ─── Paths ───────────────────────────────────────────────
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(
    r"D:\Program Files\OpenSim\Models\Gait2354_Simbody\OutputReference",
    "subject01_simbody_adjusted.osim"
)
IK_MOTION_FILE = os.path.join(
    r"D:\Program Files\OpenSim\Models\Gait2354_Simbody\OutputReference",
    "subject01_walk1_ik.mot"
)
JRA_FILE = os.path.join(
    PROJECT_DIR, "JRA_Results",
    "subject01_JointReaction_ReactionLoads.sto"
)
CALIBRATION_FILE = os.path.join(PROJECT_DIR, "opensim_calibration.json")
OUTPUT_DIR = os.path.join(PROJECT_DIR, "results")

# ─── Simulation timing ──────────────────────────────────
SIM_START_TIME = 0.0
SIM_END_TIME   = 0.36       # matches OpenSim JRA analysis window
TIME_STEP      = 0.001      # 1kHz sampling to match OpenSim output
CYCLES_PER_DAY = 6000

# ─── Subject parameters ────────────────────────────────
SUBJECT_MASS_KG = 72.6      # Gait2354 subject01
BODY_WEIGHT_N = SUBJECT_MASS_KG * 9.81

# ─── Target joints for bone-loading analysis ────────────
TARGET_JOINTS = {
    "hip_r":   {"body": "femur_r",  "label": "Right hip"},
    "hip_l":   {"body": "femur_l",  "label": "Left hip"},
    "knee_r":  {"body": "tibia_r",  "label": "Right knee"},
    "knee_l":  {"body": "tibia_l",  "label": "Left knee"},
    "ankle_r": {"body": "talus_r",  "label": "Right ankle"},
    "ankle_l": {"body": "talus_l",  "label": "Left ankle"},
}

# ─── Restoration target ──────────────────────────────────
TARGET_RESTORATION_FRACTION = 0.50

# ─── Load OpenSim calibration ────────────────────────────
# This is the key change: we now load REAL force values
# computed by OpenSim's Joint Reaction Analysis from the
# validated Gait2354 model + CMC muscle forces.

def load_opensim_calibration():
    """Load real calibration from parse_jra.py output."""
    if not os.path.exists(CALIBRATION_FILE):
        print(f"[WARN] OpenSim calibration not found: {CALIBRATION_FILE}")
        print(f"       Run parse_jra.py first. Falling back to literature values.")
        return None
    with open(CALIBRATION_FILE, 'r') as f:
        return json.load(f)

_opensim_cal = load_opensim_calibration()

if _opensim_cal:
    # Use real OpenSim values. The CMC analysis window only
    # captures the right-leg stance phase, so we mirror the
    # right-leg values to the left (gait is bilaterally symmetric).
    print(f"[CONFIG] Loaded real OpenSim calibration")

    hip_ref   = _opensim_cal["hip_r"]
    knee_ref  = _opensim_cal["knee_r"]
    ankle_ref = _opensim_cal["ankle_r"]

    EARTH_DAILY_LOAD = {
        "hip_r":   hip_ref["daily_earth"],
        "hip_l":   hip_ref["daily_earth"],
        "knee_r":  knee_ref["daily_earth"],
        "knee_l":  knee_ref["daily_earth"],
        "ankle_r": ankle_ref["daily_earth"],
        "ankle_l": ankle_ref["daily_earth"],
    }

    IMPULSE_PER_CYCLE = {
        "hip_r":   hip_ref["impulse_per_cycle"],
        "hip_l":   hip_ref["impulse_per_cycle"],
        "knee_r":  knee_ref["impulse_per_cycle"],
        "knee_l":  knee_ref["impulse_per_cycle"],
        "ankle_r": ankle_ref["impulse_per_cycle"],
        "ankle_l": ankle_ref["impulse_per_cycle"],
    }

    PEAK_FORCE_EARTH = {
        "hip_r":   hip_ref["peak_N"],
        "hip_l":   hip_ref["peak_N"],
        "knee_r":  knee_ref["peak_N"],
        "knee_l":  knee_ref["peak_N"],
        "ankle_r": ankle_ref["peak_N"],
        "ankle_l": ankle_ref["peak_N"],
    }

    print(f"[CONFIG]   Hip peak: {hip_ref['peak_N']:.0f}N "
          f"({hip_ref['peak_N']/BODY_WEIGHT_N:.2f} BW)")
    print(f"[CONFIG]   Knee peak: {knee_ref['peak_N']:.0f}N "
          f"({knee_ref['peak_N']/BODY_WEIGHT_N:.2f} BW)")
    print(f"[CONFIG]   Ankle peak: {ankle_ref['peak_N']:.0f}N "
          f"({ankle_ref['peak_N']/BODY_WEIGHT_N:.2f} BW)")
else:
    # Fallback literature values (only used if JSON missing)
    EARTH_DAILY_LOAD = {
        "hip_r":   4995000.0, "hip_l":   4995000.0,
        "knee_r":  3942000.0, "knee_l":  3942000.0,
        "ankle_r": 3416000.0, "ankle_l": 3416000.0,
    }
    IMPULSE_PER_CYCLE = {
        "hip_r":   833.0, "hip_l":   833.0,
        "knee_r":  657.0, "knee_l":  657.0,
        "ankle_r": 569.0, "ankle_l": 569.0,
    }
    PEAK_FORCE_EARTH = {
        "hip_r":   1994.0, "hip_l":   1994.0,
        "knee_r":  1709.0, "knee_l":  1709.0,
        "ankle_r": 2777.0, "ankle_l": 2777.0,
    }

DAILY_LOAD_TARGETS = {
    joint: load * TARGET_RESTORATION_FRACTION
    for joint, load in EARTH_DAILY_LOAD.items()
}

# ─── Microgravity scaling ───────────────────────────────
# In microgravity, GRF ≈ 0. Only inertial forces from limb
# acceleration remain (~5–8% of Earth JRF).
MICROGRAVITY_FORCE_FRACTION = 0.06

# ─── PID controller gains ──────────────────────────────
PID_KP = 22.0
PID_KI = 3.5
PID_KD = 2.0

# ─── Actuator constraints ──────────────────────────────
# Max torque per joint (N·m) — soft exosuit literature
MAX_ACTUATOR_TORQUE = {
    "hip_r":   25.0,
    "hip_l":   25.0,
    "knee_r":  20.0,
    "knee_l":  20.0,
    "ankle_r": 15.0,
    "ankle_l": 15.0,
}

MIN_ACTUATOR_TORQUE = 1.0

# ─── Control loop settings ─────────────────────────────
CONTROL_UPDATE_INTERVAL = 100
CONVERGENCE_THRESHOLD   = 0.95
